### ISSUE TITLE
USB OTG mode

### ISSUE THREAD

**Issue by ddosoff** [Xinyuan-LilyGO/T-Display-S3#1]
Hello LilyGO,

How can I use USB OTG mode? 
I mean there is no switch as in your previous ESP32-S2 T-Display for OTG.

**Comment by LilyGO** [comment]
The USB OTG function can be used normally

**Comment by ddosoff** [comment]
Is it possible to use default USB port as USB host? Any examples?

![lilygo-t-display-s3-esp32-s3-development-board-with-headers](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/319164/6ef10058-081d-4e87-b531-ab895ec15ead)
