### ISSUE TITLE
Quick Start, Arduino

### ISSUE THREAD

**Issue by fwt-dot-fr** [Xinyuan-LilyGO/T-Display-S3#10]
In README.md
Arduino:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pagespackage_esp32_index.json

it is:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

/gh-pages/package_esp32_index.json instead of /gh-pagespackage_esp32_index.json

**Comment by LilyGO** [comment]
Thanks for the tip, now I've fixed it.
