### ISSUE TITLE
Schematic not up to date

### ISSUE THREAD

**Issue by rolupusoru** [Xinyuan-LilyGO/T-Display-S3#102]
Hi,

Please update schematic to reflect the new 16MB flash chip 25Q128JV and nay other changes that may have taken place. it would be very useful for the community.

**Comment by teastainGit** [comment]
The schematic is a deplorable hot-mess, and is a token insult to the users.

**Comment by lewisxhe** [comment]
Sorry, I have requested to add and update it on github.
