### ISSUE TITLE
Local library copies

### ISSUE THREAD

**Issue by svdrummer** [Xinyuan-LilyGO/T-Display-S3#104]
Does anyone know how to store local libraries within the sketch folder. Swapping libraries between S3 models and other devices that use the TFT library has become painful. Even renaming the library would help.
SPI vs 8bit parallel and having two special libraries with the same name doesn't work for most people.

**Comment by mmMicky** [comment]
You can update the latest version of the TFT library, which has added the driver for this board.

**Comment by svdrummer** [comment]
I saw the new version..however... Doesn't lvgl and a few others have to be changed? According to the other T-displayS3 GitHub main module support site. The one with all the drawings and how to set up instructions. Maybe I am wrong.

**Comment by owiecc** [comment]
The best you can do is to use PlatformIO. Then you can keep the pin and library config and inside the `platformio.ini` config file. No library swapping or modification is necessary. I will submit a PR with a minimal example soon.
