### ISSUE TITLE
FTDI

### ISSUE THREAD

**Issue by Galaxy-Man** [Xinyuan-LilyGO/T-Display-S3#108]
Hi All

Can the T-Dsiaply S3 be programmed using an FTDI and not use the onboard USB port?

Which pins are exposed to enable this?

Thank you

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/224647110-d7c596f5-b3b1-4e67-b2cf-1a69654ca71c.png)

You can use the seat at the image position to access the RX TX of FTDI, 43 and 44 are the TX and RX of ESP32S3
Please note that if you use uart to upload, you must put ESP32S3 into the download mode each time you upload the program, and then upload can be allowed
To enter the download mode:
Press and hold the BOOT key on the board, don't let go, then press the RST key, then release the RST key, and then release the BOOT key. At this time, the chip is in the download mode
After downloading, you need to click the RST button to exit the download mode
