### ISSUE TITLE
Where is the BOOT button on the T-Embed please?

### ISSUE THREAD

**Issue by reflectingme** [Xinyuan-LilyGO/T-Display-S3#110]
Have one of each of T-Display, the Touch version and the T-Embed versions.  Excellent boards.

However, I am aware there is a TIP listed on the T-Display GitHub page to reset the T-Display and Touch versions by holding down the BOOT button while connecting the USB, then releasing and re uploading the code etc... Unfortunately I appear to have a non working T-Embed device and I want to do the same procedure but can't see where any BOOT button is located on the board, or how I do this boot type reset on the T-Embed device.

Could someone please let me know the similar procedure as to how I get the T-Embed device to reboot using the holding down the boot button method please?

Ta

**Comment by svdrummer** [comment]
https://github.com/Xinyuan-LilyGO/T-Embed

**Comment by reflectingme** [comment]
Yep, I have seen that page and I see there is a reference to 'Boot' in one of the diagrams towards the bottom of the page, but there is no actual physical boot button that I can see on the board that would allow me to press it whilst connecting the USB cable to start that process!!

**Comment by svdrummer** [comment]
As this is the T-display, i just thought a comment in the embed section may gain a response from people who have the T-Embed. Here, most just have the T-display.

**Comment by reflectingme** [comment]
Apparently the BOOT button on the T-Embed is the encoder button, but when I try the same process by holding down the encoder button, it still does not do the full re-boot process.  It appears I may have a dead display on my T-Embed sadly.

**Comment by svdrummer** [comment]
Hold boot pressed, Press and release reset button, then release the boot button

**Comment by reflectingme** [comment]
> Hold boot pressed, Press and release reset button, then release the boot button. Don't give up on your display...TTgo/lillygo have poor support. Put me off using these in commercial products. Good to play with though.

So when do I actually do this please...? When in this series of button presses do I connect the USB serial cable...?

And yes, I agree with you 100% - I really do like the boards, but support is sorely lacking.  My sincere thanks goes out to good folk such as you for helping as you do.  Cheers... I owe you a pint :)

**Comment by reflectingme** [comment]
> Hold boot pressed, Press and release reset button, then release the boot button. Don't give up on your display...TTgo/lillygo have poor support. Put me off using these in commercial products. Good to play with though.

I've tried doing as you suggest but I reckon I received a dead display.  Code appears to compile and upload successfully, the LED's do some stuff, but the display sadly, remains as dead as a Dodo!!!

**Comment by teastainGit** [comment]
Did you raise an Issue over at the T-Embed GitHub repository ?
I do not have a T-Embed to test…but a common problem with the LilyGO T-Display S3 is the TFT_eSPI library must be the EXACT one supplied for your model of LilyGO  and not the latest Bodmer and certainly NOT the one supplied by Arduino OR doing a “Arduino Library Update"



Cheers !
Terry Stainton

***@***.***

**Comment by lewisxhe** [comment]
T-Embed  dT-Embed's BOOT button is located in the middle of the rotary encoder. Sorry, this reply is a little late. I hope you have solved this problem

**Comment by reflectingme** [comment]
> T-Embed dT-Embed's BOOT button is located in the middle of the rotary encoder. Sorry, this reply is a little late. I hope you have solved this problem

Thanks Lewis, I have managed to resolve the issue but it wasn't due to the BOOT button reset process, it was down to the T-Embed display drivers and the TFT_eSPI library - which if used with this board, required a specific TFT_eSPI library available on the T-Embed LilyGo GotHub pages, and **NOT** the one generally available library from Bodmer.

**Comment by lewisxhe** [comment]
This warehouse was previously maintained by Micky, and may not be used for some reasons<TFT_ ESPI>, if I have time next, I will use Bodmer's<TFT_ ESPI>test to see if it can be used

**Comment by DERECHTEMULDE** [comment]
i also have this problem can you help me
