### ISSUE TITLE
Color calibration Issue (reds are Orange)

### ISSUE THREAD

**Issue by doh38** [Xinyuan-LilyGO/T-Display-S3#113]
Hi,
The colors are quite off which is a bit sad seeing the good quality of the display.
-To make it short. it's impossible to get an acceptable "red". 0xF800 is Orange at the best.
-Light_Grey 0xCDF9 for instance is quite ok when looking close to the display, but will emit green tint when  the "observant" goes a bit away from screen.
I have seen some kind of gamma settings/ color correction tool in the ST7789V driver. But I have no Idea how to correct this. Is there some "tutorial/info?" 
Or it is an Hardware thing I may have to live with it?
Gruß,
![LMC_20230303_065935_8 4 300](https://user-images.githubusercontent.com/42808575/222643268-d0f95c46-dfef-4175-b979-3f8d3633597b.jpg)

**Comment by teastainGit** [comment]
Me too!
![REDORANGE1024](https://user-images.githubusercontent.com/80008504/222794398-e23dbc74-a7e1-4a3a-90c2-f5b82e5ab17c.jpg)

**Comment by lewisxhe** [comment]
Sorry, the current initial gamma value is provided by the screen manufacturer. I don't know how to calibrate the gamma value. These values are generally provided by the screen manufacturer. I have already fed back to the screen manufacturer to see if they have any solutions

**Comment by doh38** [comment]
very good, please et us know when you get a reply. it's actually very present, and as soon as LilyGo sells a "display" it's somehow mandatory that it somehow shows color close enough to expectations. As it is now, the reds are simply impossible to draw except with some "hacking" of rgb values to compensate (only at some brightness settings) the mismatch. :)
