### ISSUE TITLE
USB C Pins

### ISSUE THREAD

**Issue by Aieser** [Xinyuan-LilyGO/T-Display-S3#114]
Hello, I can't find in the schematic an USB C conector. Is this connected to 19 and 20 GPIO pins? Thanks!

**Comment by teastainGit** [comment]
Yes!
ESP USB DM
ESP USB DP

￼

￼

Cheers !
Terry

**Comment by Aieser** [comment]
> Yes! ESP USB DM ESP USB DP ￼ ￼ Cheers ! Terry
> […](#)

Thanks!
