### ISSUE TITLE
Lilygo S3 won't upload known working sketch...on CPU that programs many of these.

### ISSUE THREAD

**Issue by chrisedgedotcom** [Xinyuan-LilyGO/T-Display-S3#115]
INO, Cable, USB port, etc. all the same as usual. I program lots of these with the same code.

When it finally says connecting, the screen does NOT go blank, it reloads the demo sketch and never takes the code. Here is the error I am getting. 

Connecting....Traceback (most recent call last):

  File "esptool.py", line 34, in <module>
  File "esptool\__init__.py", line 1004, in _main
  File "esptool\__init__.py", line 646, in main
  File "esptool\__init__.py", line 895, in get_default_connected_device
  File "esptool\loader.py", line 631, in connect
  File "esptool\loader.py", line 572, in _connect_attempt
  File "esptool\loader.py", line 435, in sync
  File "esptool\loader.py", line 365, in command
  File "esptool\loader.py", line 317, in write
  File "serial\serialwin32.py", line 325, in write
serial.serialutil.SerialTimeoutException: Write timeout
[16916] Failed to execute script 'esptool' due to unhandled exception!
An error occurred while uploading the sketch

I am on the right port, and it shows that it's there. 
I only see ONE button, the RST one, and not sure how to get it into a loading mode. (I saw people mention another button...I don't see one on the S3)

Let me know if it's defective or?

**Comment by svdrummer** [comment]
that all reads like an esptool issue. They have had an issue with the latest arduino esp32 upgrade. It was -re-released two days later. Esptool had to be upgraded. I am not seeing anythin chip related there

**Comment by chrisedgedotcom** [comment]
I have programmed about 10 S3's today. This is the only one that is not taking the same code as the other 10!

**Comment by teastainGit** [comment]
D) In the Port Selection, if the USB flickers on and off and you cannot upload, you may have to 
	manually enter "Upload Mode".
	This can be caused by a faulty sketch that is running at high speed with no delay at the 
	end of the loop, or working with Dual Cores.
 	To enter Upload Mode:
	press Boot and hold, press reset and release, then release Boot and go it into "Upload Mode"

The Boot button is above or to the left of the USB, “GPIO 0”.
	
From my LilyGO T-Display S3 setup and example repository here:
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples/blob/main/LilyGO%20T-Display-S3%20Setup.txt

Hope this helps, Terry

**Comment by chrisedgedotcom** [comment]
That actually let it upload but nothing on display now. I will try that again, and see if doing it again makes it stick.

**Comment by chrisedgedotcom** [comment]
That worked! Thank you to everyone.
