### ISSUE TITLE
Strange and high values returned from touch pin.

### ISSUE THREAD

**Issue by Rollmops67** [Xinyuan-LilyGO/T-Display-S3#119]
Hello !
It's the first time I try to work with a GPIO as a Touchpin on the T-Display. (and on an ESP32)
Tutorials say when I read a touchpin without touching it the value is ABOUT 100 and when I touch it, it can drop bellow 20.

My T-Display behaves completely different.
When I read the pin with `Serial.println(touchRead(T13));` or `Serial.println(touchRead(13));` I have a value of about 12500 without a wire connected.
When i solder an 3 inch long wire on pin 13 the value (without touching) rises to about 15000.
When I touch it through the insulation, the value rises to about 20000 (first bump on the image bellow), and when I touch the end of the wire (insulation removed) the value climbs (slowly) to about 100000. (second bump)
![image](https://user-images.githubusercontent.com/122739954/224418571-c9fec1da-a212-41e5-bd6a-9aa868384f29.png)

So OK, I can see a difference, but is this behaviour normal  for a T-Display ?
Do I have to declare something in the setup ?
Thanks for any tip !

Roland

**Comment by lewisxhe** [comment]
Touch is easy to receive interference from external magnetic field. It is based on capacitance. I don't recommend you use touch function. TP223 may be a better choice
