### ISSUE TITLE
wifi is very weak

### ISSUE THREAD

**Issue by Arielhh** [Xinyuan-LilyGO/T-Display-S3#123]
I am looking for advice on why the wifi is so weak on this device.
I am using the internal antenna. I tried different T-Diaplay S3 units with the same results.
Other ESP32 development boards (which are not T-Display S3) are working fine.
I also tried an external antenna (moved the 0 ohm resistor to the right location) with the same poor results. 
Maybe the Bluetooth and BLE transmitters are interfering. How can I power them off?

**Comment by lewisxhe** [comment]
Can you provide a picture of the antenna section?

**Comment by Arielhh** [comment]
You can see it here: https://www.lilygo.cc/products/t-display-s3

**Comment by Arielhh** [comment]
> Can you provide a picture of the antenna section?

You can see it here: https://www.lilygo.cc/products/t-display-s3

**Comment by kdg3737** [comment]
This is terrible, also seeing ping times of 200ms and more. Tested with bluetooth disabled, on both ESPIDF and Arduino, same result. Looks like a hardware issue. Please Lilygo check your Wifi signal before throwing these boards in production. It's a great board but this weak Wifi signal makes it unusable for +95% of applications.

**Comment by richardsg307** [comment]
I've spent several days replacing my old ESP8266 Boiler monitor with a brand spanking new T-Display-S3, Tasmotised and showing lots of useful data, only to install it and find it won't connect to my WiFi! I've ordered an Antenna to see if it makes a difference; judging from other comments it won't. Anyway, do I need to remove a jumper or something?

**Comment by Arielhh** [comment]
Agree, wifi is very bad.  in ESP32 S2 there was no Bluetooth support and it was working perfectly. Maybe there is a collision between Bluetooth and wifi. Is it possible to turn off completely the Bluetooth?

**Comment by lauba11** [comment]
I have had the same experience with this board. Has anyone improved the situation with the WiFi signal?:)

**Comment by richardsg307** [comment]
I bought a Tapo WiFi Extender of Amazon for £14.99 (2.4 Band only). It show 1 bar of 5 for the incoming wifi strength in my boiler location but the T-Display-S3 connects to it solidly.

**Comment by besanur** [comment]
i have the same problem, very weak wifi, i have tested my custom code also some other firmware such nerdminer.. my wemos s2-mini has much better wifi quality

**Comment by Arielhh** [comment]
> i have the same problem, very weak wifi, i have tested my custom code also some other firmware such nerdminer.. my wemos s2-mini has much better wifi quality

Use external antenna

**Comment by besanur** [comment]
no i don't want to use external antenne, i will use another device and send this back

**Comment by kdg3737** [comment]
I noticed ALL my S3 boards have this weak wifi issue, not just LilyGO. Sticking to S2 for now and praying they'll fix it in the S4.
