### ISSUE TITLE
no Touch IC found

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-Display-S3#125]
1) I copied all libs to my lib folder
2) Then I compile "....T-Display-S3-main\example\touch_test\touch_test.ino" 
3) Logo is flashing and I see 100ms a green text but then display turns black Serial and serial print says:
---------------------------------------------------
Hello T-Display-S3
226): GPIO output gpio_num error
E (514) gpio: gpio_set_level(226): GPIO output gpio_num error
Touch IC not found
---------------------------------------------------
4) when I press BOT button, system goes to sleep! good!
5) when I touch display, system wakes up!!!! yeah, so touch function works in principally...but why GPIO error???

What is wrong???

**Comment by 369Martin369** [comment]
Is my unit broken? I checked SCL=18 and SDA=17, so compiling should be fine

**Comment by AlexanderDragosch** [comment]
same error here.
any new insigthts ?

**Comment by AlexanderDragosch** [comment]
worked after i changed to "SELF" 
```
//#define TOUCH_MODULES_CST_MUTUAL
#define TOUCH_MODULES_CST_SELF
```

**Comment by 369Martin369** [comment]
thank you lex. can confirm function now. 
PS. P value is always 0000...so pressure does not work. However, axes are okay.

**Comment by 369Martin369** [comment]
Lilygo, please patch file "touch_test.ino" with 
//#define TOUCH_MODULES_CST_MUTUAL
#define TOUCH_MODULES_CST_SELF

Thanks

**Comment by lewisxhe** [comment]
The t-display s3 has two types of touch screens, with a small hint at the top of the sketch that may not be obvious enough

**Comment by lewisxhe** [comment]
I have already marked a clear hint above the sketch

**Comment by 369Martin369** [comment]
can you explain about P value is always 0000... and why multiple fingers are not detected? It this because of new chip?

**Comment by lewisxhe** [comment]
Most TFT touch screens do not support multi touch

**Comment by 369Martin369** [comment]
Please a bit more specific....so you ship a mix ...some work,.some not, depending on chips used, or what???thanks

**Comment by 369Martin369** [comment]
![20230323_131914.jpg](https://user-images.githubusercontent.com/26202033/227202345-6fd063bf-2ff1-4c31-9244-24f1ea88f81d.jpg)

2nd. You ship box with picture of a keyboard. It would be nice if you can share the code of the keyboard with us, so that we can speed up our developments. Thanks a lot!

**Comment by 369Martin369** [comment]
> Keyboard, please look here https://github.com/Xinyuan-LilyGO/T-Embed/tree/main/example/factory

I have no idea which code lines you refer to...

**Comment by Ton-O** [comment]
Hi, I have a LilyGo T-display S3 and want touch to work. according to the seller, the touch chip has been changed from CST328 to CST816... What settings should I use for touch i that case?
