### ISSUE TITLE
Serial Monitor displays nothing.

### ISSUE THREAD

**Issue by igoralves1** [Xinyuan-LilyGO/T-Display-S3#126]
I bought a LilyGo Soldered pin S3 board no touch screen. 
I am using Mac Monterey 12.6.3 M1 and Arduino IDE 2.0.5.
I am using the example `arduino_gfx_demo` to test the board.
If we analyse the code in the file [arduino_gfx_demo.ino](https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/example/arduino_gfx_demo/arduino_gfx_demo.ino) in the line 21 we should expect the output `Hello T-Display-S3` in the `Arduino-IDE Serial Monitor`. 
When I upload the code I can see all the `printnice` output in the T-Display but I cant see the `Serial.println("Hello T-Display-S3");` in the Serial Monitor.
I also tried to display in the terminal using the `ls /dev/tty.*` to identify the boad port and the `screen /dev/tty.usbmodem2101` to display the serial monitor info.

I am following all the settings suggested in the `README.md > correct settings in the Tools menu` but I see nothing. No displays.

Is there any process that is publishing all outputs to the board screen?

**Comment by teastainGit** [comment]
Have you displayed serial on this board with a simpler sketch!?

**Comment by teastainGit** [comment]
OK, looks like a simple enough test sketch ;)
I am using Arduino 2.0.4 not the beta nightly build.
I am running ESP32 v2.0.6.
I will try and duplicate your problem tonight.
Sometimes I have to push the little reset button on the back and try toggling the serial controls to the right of the serial monitor, especially the “timestamp”.

**Comment by teastainGit** [comment]
I have an extensive LilyGO T-Display S3 GitHub repository with all the problems I (and others) have faced, here:
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples
They keep changing the setup config advice!  Here is a screen shot from their ReadMe from  December 2022:
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples/blob/main/Arduino_Config.png
The difference that I see that impacts Serial Monitor is this one: 
"USB DFU On Boot | Enabled" is the new setting.
I'm not sure what it does but I have always followed the previous advice and "Disabled"
Hope this helps, keep me informed!
-Terry

**Comment by lewisxhe** [comment]
Have you turned on CDC? As shown below
![image](https://user-images.githubusercontent.com/22990954/226497907-da1b1f36-6caf-4d2c-8274-29af5ee5f4ec.png)

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/firmware

**Comment by teastainGit** [comment]
"> I uploaded a firmware that displays and prints time stamps. Please try it out https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/firmware"

What does this firmware do?
I asked in another Issue about the bootloader being protected in ROM and cannot be damaged.
I thought that the only program  in a board is the bootloader and your sketch?
Thank you, Terry

**Comment by lewisxhe** [comment]
Sketch > https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/example/TFT_Rainbow
Install Esptool > https://github.com/RavenSystem/esp-homekit-devices/wiki/Install-ESPTool-on-macOS

Let you brush in the firmware I provided to see if this board works properly Now, don't you say you can't output any messages to Serial?

**Comment by LucaZiegler** [comment]
> @lewisxhe It is working. This is what I did:
> 
> 1. Installed ESPTOOL -> `python3 -m pip install esptool`
> 2. `CD` to the firmware folder -> `https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/firmware`
> 3. Ran your code -> `esptool --chip esp32s3 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 16MB 0x0 bootloader.bin 0x8000 partitions.bin 0xe000 boot_app0.bin 0x10000 firmware.bin`
> 4. Rainbow is in the device screen
> 5. Opened the ArduinoIDE in any project and connected to the board port
> 6. Display millis is ok, as we can see in the picture.
> 
> <img alt="Screen Shot 2023-03-23 at 8 46 29 AM" width="1140" src="https://user-images.githubusercontent.com/3280251/227211356-4cf355d3-e0ae-48aa-b89b-969a3dfb36e7.png">
> 
> 7. opened a previous project `simple hello world`.
> 8. uploaded it to to the board with the same configuration as 2 days ago
> 9. Now I see hello world in the display.
> 
> <img alt="Screen Shot 2023-03-23 at 8 57 01 AM" width="1111" src="https://user-images.githubusercontent.com/3280251/227211792-cc2ac090-642c-4137-abd5-f78032fe360d.png">
> 
> 10. And also can verify `Serial.print` from other projects.
> 
> <img alt="Screen Shot 2023-03-23 at 9 03 54 AM" width="1145" src="https://user-images.githubusercontent.com/3280251/227213162-79bb906c-53ae-4a4b-a74f-7797ab19e7a0.png">
> 
> All is good but what is different now? What was the issue? The only different thing in my machine is that I have installed ESPTOOL but I think this is not what is making the difference. I will close the ticket. Thanks

Yes I now got an output, but with a new sketch not anymore.

**Comment by LucaZiegler** [comment]
OK ...found it .. for the Lilygo T-display S3 you have to set USB CDC on Boot "Enable".

**Comment by dental-informatics-org** [comment]
It seems that this error is related to another error that I posted [here](https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/138).

In the 138 issue AND maybe here, it seems that there is a physical issue with the flash memory. I had to replace the board and I bought another ESP32-S3 from another vendor. 

The brand new `LilyGO` board and the other brand new board are still showing the same issues: sometimes it does not finishes the upload process (issue 138) and sometimes it still do not shows the output in the `Serial Monitor`.

In 100% of the time when I follow the instructions suggested by @lewisxhe in this [topic](https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/126#issuecomment-1478772413) it shows the output in the Serial Monitor, pressing the boot.
But not all that times I have the firmware uploaded (issue 138).

All that is leading me to conclude that there is something in the software or in the OS MAC

**Comment by lewisxhe** [comment]
Hi  @igoralves1 

From what you conclude it has something to do with your OS?

**Comment by obejohn** [comment]
I had a similar issue with a Lilygo T-QT ESP32-S3 board.  Lewisxhe's suggestion to set USB CDC on boot to "Enabled" solved my issue. Interestingly, the issue wasn't evident when using the Seeed-XIAO-ESP32C3 or the Lilygo T Display boards, even with USB CDC on boot set to "Disabled". Go figure.

One difference between my settings (that worked) and igoralves1's settings is I don't have USB DFU on boot "Enabled". 

A very BIG thank you to Lewisxhe for solving my issue.

> Have you turned on CDC? As shown below ![image](https://user-images.githubusercontent.com/22990954/226497907-da1b1f36-6caf-4d2c-8274-29af5ee5f4ec.png)

**Comment by Davidog0321** [comment]
Hi I came across this issue trying to print "Hello, world!" to serial monitor, my issue was resolved by setting USB CDC On Boot to "Enabled".
Board : Lilygo T-QT ESP32-S3
OS : Windows 10
Arduino IDE Version : 2.3.2
![Screenshot (1)](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/105672798/7eb9d4e3-9579-465e-a73b-fb4e07d5ffa6)
Thank you.

**Comment by summerfind** [comment]
Hi.
my T-Display S3 on Arduino IDE, works well only when serial monitor is open, if close it no luck, why so?

**Comment by pjeantaud** [comment]
In Tools, try "USB CDC on Boot »  > Disabled

**Comment by ScriptBlock** [comment]
Holy shit thank you.
