### ISSUE TITLE
The JST-SH 1.0mm could not be I2C?

### ISSUE THREAD

**Issue by hengying** [Xinyuan-LilyGO/T-Display-S3#127]
I try to use the _STEMMA QT / Qwiic JST-SH 1.0mm 4-PIN_ (G 3V 43 44) on an I2C device, but it seems not work.
I changed to GPIO1 and GPIO2, it worked. According to the ESP32S3's datasheet, it seems 43 and 44 could be used on I2C.

U0TXD, GPIO43, CLK_OUT1
U0RXD, GPIO44, CLK_OUT2

I wonder could GPIO43 and GPIO44 be used on I2C?

What's the usage of the JST 1.0 port?

**Comment by teastainGit** [comment]
The JST-SH 1.0mm 4-PIN (G 3V 43 44) is SDA 43, SCL 44:
Wire.begin(43, 44);  //SDA, SCL
Here is an image that I updated:
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples/blob/main/T-DisplayS3_Pinout.png
I use the 4 pin with I2C, no problem.
What device are you connecting to?
