### ISSUE TITLE
half of the display with garbage

### ISSUE THREAD

**Issue by guideon** [Xinyuan-LilyGO/T-Display-S3#128]
Hi, I have two t-display-s3 boards one is working fine and the other one is having half of the screen with garbage and a black mask. I have tried everything but when I upload a sketch with Arduino 2 it is not displayed on the entire screen. I am not so good in MCU and did not find a way to reset to factory default. Help would be appreciated.

**Comment by lewisxhe** [comment]
This may not be possible, as it may be a screen burning phenomenon similar to OLED.

**Comment by dejavu1987** [comment]
I have broken my lcd while placing it on a breadboard. Where do I find a replacement screen, and can you suggest how to remove the broken screen from the board?
<img width="1214" alt="Screenshot 2023-04-22 at 10 13 07" src="https://user-images.githubusercontent.com/1720245/233771948-64de2472-1984-4178-b6b9-42fed35fe89a.png">

**Comment by svdrummer** [comment]
These are fragile screens. I have several that fall apart due to warmer climates. They are easy to pull apart, or in my case, fall apart. I would be interested in replacement displays also.

**Comment by 369Martin369** [comment]
OMG...you broke it? get a new one....

**Comment by mickeyl** [comment]
Well, it's 35€ here, so I won't do that when it is **that easy to break by putting it into a breadboard…** it still works as a "normal" S3 development board, which is good.

**Comment by dejavu1987** [comment]
> Well, it's 35€ here, so I won't do that when it is **that easy to break by putting it into a breadboard…** it still works as a "normal" S3 development board, which is good.

Minus all the pins used up by the display :(
