### ISSUE TITLE
T-Display-S3 Touch  - 3D housing DRAFT V1.0 available

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-Display-S3#131]
fyi: 
I designed a case for beloved touch.... 2 prints only....works on FDM printer with 0,4mm nozzle
https://www.thingiverse.com/thing:5933982/files
https://a360.co/42BD9iV

**Comment by bratoff** [comment]
How would you feel about sharing the source files in a git?  That would allow others to tweak as necessary for their printers.

**Comment by 369Martin369** [comment]
here we go, Fusion360 format
[T-Display-S3-Touch_V19.zip](https://github.com/Xinyuan-LilyGO/T-Display-S3/files/11075311/T-Display-S3-Touch_V19.zip)

**Comment by 369Martin369** [comment]
please follow project in Thingiverse

**Comment by bratoff** [comment]
> please follow project in Thingiverse

Thingiverse contains only the STLs.  I was asking about the files from whatever CAD tool you used to create the STL.  That would facilitate making any necessary tweaks to get it to print on a different printer.

**Comment by 369Martin369** [comment]
> > please follow project in Thingiverse
> 
> Thingiverse contains only the STLs.  I was asking about the files from whatever CAD tool you used to create the STL.  That would facilitate making any necessary tweaks to get it to print on a different printer.
> 

Files were added. Have fun

**Comment by lewisxhe** [comment]
@369Martin369 Thank you for your contribution. Can I add links or files to the warehouse's homepage?

**Comment by 369Martin369** [comment]
> @369Martin369 Thank you for your contribution. Can I add links or files to the warehouse's homepage?

Sure, however you want...also source files from zip file

**Comment by lewisxhe** [comment]
Thank you, I have added and explained the source
