### ISSUE TITLE
3D file for non-touch basic screen is missing

### ISSUE THREAD

**Issue by seiferth** [Xinyuan-LilyGO/T-Display-S3#133]
Hi,

I've imported the 3 stp files in the 3D_file folder into Inventor and realized that there are two files containing the model of the touch screen, but none containing the model of the non-touch version. 
See the screenshot below:
![image](https://user-images.githubusercontent.com/2724494/228928058-86e045ef-9eb4-422f-8be8-6b24f5e5d445.png)

Could you also upload the non-touch version 3d files?

Best,
Hagen

**Comment by lewisxhe** [comment]
I'll add it later

**Comment by lewisxhe** [comment]
Done !

https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/3D_file/noTouch.stl
