### ISSUE TITLE
Micropython

### ISSUE THREAD

**Issue by Valadimirovich** [Xinyuan-LilyGO/T-Display-S3#134]
You can add pre-compiled firmware from https://github.com/russhughes/st7789s3_mpy

**Comment by lewisxhe** [comment]
Thank you for your contribution. Can I add a link to the warehouse homepage?

**Comment by Valadimirovich** [comment]
I believe you can check about that with the author, I'm just shearing that I found it way easier to use pre-compiled version, there is beta version in development as well from the same author

**Comment by lewisxhe** [comment]
Can you give me a link?

**Comment by Valadimirovich** [comment]
https://github.com/russhughes

**Comment by lewisxhe** [comment]
Thanks
