### ISSUE TITLE
What does brushing in a binary do?

### ISSUE THREAD

**Issue by teastainGit** [Xinyuan-LilyGO/T-Display-S3#137]
Some people feel that they have bricked their LilyGO T-Display S3 and Lewis He advice is to brush in a binary, perhaps a "BootLoader"?
I thought that the ESP32 S3 had a permanent indestructible BootLoader burned into ROM when the chip was made by Espressif?
What does brushing in a BootLoader do, exactly?
Thanks, Terry

**Comment by lewisxhe** [comment]
esp32 属于两级引导模式，一级引导属于不可更改，所以esp32 永远都不可能刷成砖.

写入的bootloader属于二级引导程序，如果用户在写入固件过程中断开或者写入错误的文件，那么重新写入二级引导程序确保二级引导是正确的。

如果你关心过烧录过程，就可以发现每次上传草图的时候都会上传 bootloader.bin
![image](https://user-images.githubusercontent.com/22990954/230246202-15260210-0c0c-4714-b9cb-48b4e95b24e8.png)

**Comment by teastainGit** [comment]
Thank you Lewis
-Terry
