### ISSUE TITLE
Library path Arduino 2.0

### ISSUE THREAD

**Issue by Bogdan50** [Xinyuan-LilyGO/T-Display-S3#14]
I am having difficulties adding/recognizing the libraries to the path.
Could you please show how to add those for the new Arduino IDE 2.0?

![image](https://user-images.githubusercontent.com/48182673/192611528-e56cb838-e252-4953-9f66-26a8e79437cd.png)

**Comment by robertlugg** [comment]
@Bogdan50 , The `lib` files should be moved to your _sketchbook_ and NOT where the system ones are.  So, on Windows, mine is in .../Documents/Arduino/libraries/
![image](https://user-images.githubusercontent.com/6054540/192983512-cc844764-f929-4d6d-8b63-52bf9d5a7993.png)

I still can't upload to the S3 though.  What is the name of the board you are using in the Arduino IDE?

**Comment by LilyGO** [comment]
The sample program needs to rely on the files in lib to compile. The way to use it is to copy the files in the lib to the user's Arduino/libraries folder. In Arduino 2.0.0 it is possible to automatically upgrade the version of the library. I have made minor modifications to this TFT library. So there will be a problem that it cannot be used after being upgraded. It is recommended not to upgrade the version of the library or patch the latest board library.
