### ISSUE TITLE
Unable to power board with wall plug, but computer USB-C works!

### ISSUE THREAD

**Issue by jessedmatlock** [Xinyuan-LilyGO/T-Display-S3#143]
I've been programming and testing the board using a USB-C cable connected to my computer - typical setup.. nothing fancy (Apple iMac, USB port on the keyboard)

BUT, when I connect the SAME cable to any wall wart (power adapter), the board fails to load or it loads the initial image (setup())  and doesn't run the loop().

I've tried several 5v wall power adapters, and which prove good when powering other USB-C devices, with the same cord I'm testing the display with.. ..

Any thoughts?

**Comment by jessedmatlock** [comment]
Further testing, I used the same USB-C cable and a large battery bank (used for charging cell phones on the go).. and the display works. 

So, in closing,.. no 5v power adapter, regardless of wattage capability, will power the display fully.

Anyone else having this issue? Any suggestions?

**Comment by jessedmatlock** [comment]
Thank you! Great suggestion.. I uploaded a known good sketch, set GPIO15 to HIGH, it powered on PC USB as well as Wall Plug just fine.. no issues. 
I will work with the programmer to address the code and see if we can find what is causing this..


On Apr 24, 2023, at 12:51 PM, Terry Stainton ***@***.***> wrote:


I want to help but It seems an impossible situation! I have several for 7 months(!) and they will power from anything, including iPhone white cube chargers, so, I wonder if there is some upload in your LilyGO T-Display S3 that is the problem?
Have you uploaded a simple known good sketch that that used to run when you got it?
What do you think has changed?
-Terry

**Comment by teastainGit** [comment]
Good news!
I have a community resource on GitHub here:
Https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples 
You may find something useful!

Cheers !
Terry

**Comment by richp-tech** [comment]
May I ask a question? I can't get the Lilygo T Display to mount in my MacBook Air. Any ideas? I have installed both drivers mentioned in the GitHub. I can see the device in the USB tree. Thanks.


![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/4f2a494c-8017-4e4e-a652-de5f2719830c)

![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/f36a06d0-c42c-45d4-88a4-2fc85cb68136)

**Comment by teastainGit** [comment]
You have a 'TTGO' (!) not a LilyGO T-Display S3.
So use my GitHub repository with that in mind!
What programming environment are you using?

**Comment by richp-tech** [comment]
Hello @teastainGit 

It's very kind of you to reply. The box says T display. My issue is getting it to mount on my MacBook Air. Are you saying I'm using the wrong drivers because I don't know what the board is? 

I'll take another look, thank you.

![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/d639da20-5337-4f43-a4cb-d25ab561ccb4)

**Comment by lewisxhe** [comment]
> Hello @teastainGit 
> 
> It's very kind of you to reply. The box says T display. My issue is getting it to mount on my MacBook Air. I installed the drivers which are in GitHub pdf for this device.
> 
> But it won't mount.
> 
> Thank you
> 
> ![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/d639da20-5337-4f43-a4cb-d25ab561ccb4)
> 
> https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/da7875c0-90be-46db-86b5-3d3062f29830
> 
> ![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/fb5efd9b-8ef2-4ba2-bf01-182b2630e56b)

https://github.com/Xinyuan-LilyGO/TTGO-T-Display

**Comment by richp-tech** [comment]
Hi @teastainGit 
Thanks for your reply. I see. Sorry about that. Lots to learn and I misunderstood. No combination of button holds and clicks makes a difference. This is an M1 Macbook Air. Thanks for your help.
Rich

**Comment by teastainGit** [comment]
With a modern Mac, one does not usually go to the Settings USB page to check if your ESP32 is connecting.
Are you using Arduino IDE ?
You can watch live connection, loss of connection right here:
<img width="827" alt="Screenshot 2024-01-29 at 2 35 29 PM" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/80008504/6eadbc1e-e08c-4926-bb9a-31870c8fc0ed">

and 

<img width="814" alt="Screenshot 2024-01-29 at 2 35 46 PM" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/80008504/3a6dec94-f209-4955-9220-48be12618e37">

**Comment by richp-tech** [comment]
Hi, that's what I expected. I was surprised I had to install drivers (I installed them both). It won't mount. I will show up in the terminal (twice) and in the USB tree (once) plus twice in Arduino. I have mashed it up somewhere.
<img width="278" alt="Screenshot 2024-01-29 at 19 43 18" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/68530fff-29c0-492a-bf86-5716183a85d1">
<img width="196" alt="Screenshot 2024-01-29 at 19 42 04" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/5b612d37-1947-4b7f-8754-ef8ee56cf755">
<img width="255" alt="Screenshot 2024-01-29 at 19 41 24" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/e3fbebd1-e9bd-485e-8fe0-6ab70013cf41">

**Comment by richp-tech** [comment]
<img width="293" alt="Screenshot 2024-01-29 at 19 47 13" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/a18f0934-3739-4c7f-90f6-f7c08e01b0ab">

**Comment by teastainGit** [comment]
The 'Board Info' feature on Arduino IDE where it tries to "Guess  Your Board"  is useless for ESP32 and serves as an upsetting distraction, solely.
Have looked at the Arduino IDE  "Select Other Board and Port"? whilst connecting, as I showed?
Also M1 Macs are very fussing about USB versus Thunderbolt. MY LilyGO products only connect using TB cables in the TB ports on the back...my older non S3 boards only connect to the native USB ports on the back.

**Comment by richp-tech** [comment]
Hi @teastainGit I cracked it. It was my understanding of GitHub and libraries which you helped me fathom. A clean install made all the difference. Thanks very much! It was very kind of you. A huge leap forward in  my grasp of it. 
![success](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/59874838/ba7d1aeb-7685-45f4-9a09-4860b8edd02f)

**Comment by teastainGit** [comment]
Great to hear!!!
Cheers, -Terry

**Comment by richp-tech** [comment]
Thanks again @teastainGit 
I'm just an artist with an interest in tech. You have helped greatly
