### ISSUE TITLE
T-Display-S3 and which TFT_eSPI library to use?

### ISSUE THREAD

**Issue by git2212** [Xinyuan-LilyGO/T-Display-S3#146]
Hello.

There seems to be a rather strong recommendation about NOT using the official TFT_eSPI library with T-Display-S3 (arduino core) but rather to use the forked version from [https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/lib/TFT_eSPI](https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/lib/TFT_eSPI) instead.

Given that development has been progressing, is this still the recommendation for v 2.5.0 of the official version considering that users are now reporting that the T-Display-S3 is working with v 2.5.0?

My next question is, it appears the Xinyuan-LilyGO version of the TFT_eSPI library has added features, is there a plan to merge these features into the official version at some point?

Thx.

**Comment by lewisxhe** [comment]
This is not a forked version, but a TFT_ The main branch of eSPI, although not the latest, is a version after the addition of T-DisplayS3, and LilyGo has not made any modifications
