### ISSUE TITLE
Arduino_gfx_demo from example got compilation error

### ISSUE THREAD

**Issue by Rewonka** [Xinyuan-LilyGO/T-Display-S3#147]
Hello,
I'm a beginner and when I tried to compile and upload the arduino_gfx_demo I get compilation error:
cannot convert 'const char*' to 'const __FlashStringHelper*'
Can somebody explain how to solve it ?

The full log is in the file.
[Output_for_arduino_gfx_demo_ArduinoIDE210.txt](https://github.com/Xinyuan-LilyGO/T-Display-S3/files/11376174/Output_for_arduino_gfx_demo_ArduinoIDE210.txt)
Thank you!

**Comment by teastainGit** [comment]
Hi! I just downloaded it and it complied first time and runs OK.
I am using Arduino IDE v2.1.0
Board def ESP32 V2.0.6
And all the libraries straight from the LilyGO github repository, with NO Arduino Library Updates!

Has your LilyGO T-Display S3 run other sketches fine up to now?
