### ISSUE TITLE
tft example not working but TFT_Rainbow is working

### ISSUE THREAD

**Issue by krupis** [Xinyuan-LilyGO/T-Display-S3#153]
Hello. I have received T-Display S3 development board. I have tried to flash some example programs to check how it works and I notices that when I flash the example "tft" I only get the black screen and the following is displayed in the serial terminal:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4202619e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
Hello T-Display-S3
```

However, when I flash the "TFT_Rainbow" example, everything seems to be working fine. The following is displayed on the serial terminal:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x42023f3e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
E (14) gpio: gpio_set_level(226): GPIO output gpio_num error
E (15) gpio: gpio_set_level(226): GPIO output gpio_num error
Current running 3743 millis
Current running 4781 millis
Current running 5783 millis
```

What could be wrong with the tft example?

**Comment by Mategm** [comment]
Could You copied from the git repo lib folder into your Ardiunio Lib folder? 
After that, and choosed  the ESP32S3 Dev Module its worked for me, only an output error for gpio, on serial monitor, but the display works fine.
