### ISSUE TITLE
I2C GPIO pins for touch driver

### ISSUE THREAD

**Issue by krupis** [Xinyuan-LilyGO/T-Display-S3#154]
I have noticed a mistake. I2C pins are declared as following in the image:

SDA = 17
SCL = 18
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/22237034/1aada744-3153-4450-8bf9-97821bbc0919)

However in the schematic they are wired the other way around:
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/22237034/779edc97-d454-47b2-87eb-cce9cfe3e4fc)

Is that an error or I am misunderstanding something? :)

**Comment by lewisxhe** [comment]
thanks for feedback

**Comment by svdrummer** [comment]
Closed without an answer to a legitimate question. Which one is correct.

**Comment by lewisxhe** [comment]
Oh, sorry .
The schematic is correct and the sketch is marked
The pin diagram has been updated

**Comment by paco3346** [comment]
Sorry to necro but I spent a good hour trying to figure out what's happening here.

The screenshot above (where you actually see the LCD) is incorrect and the second image (with the turned text) is correct. The image on the [manufacturer's site](https://lilygo.cc/products/t-display-s3) is still incorrect as of this writing.

To make it _abundantly_ clear:

```
sda: 18
scl: 17
```
