### ISSUE TITLE
Clarification regarding I2C and touch pins

### ISSUE THREAD

**Issue by krupis** [Xinyuan-LilyGO/T-Display-S3#157]
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/22237034/dd264900-94a2-4594-ab34-0e81b0951487)
From what I understand these pins are used for the Display touch.

So If I use the Touch fnctionality on my display, I am not allowed to use these pins for anything else.

However, If I do not use the touch, can I use these pins for whatever I want? Is that going to cause an issue with the display?

**Comment by lesept777** [comment]
I2C is a bus, so you can use it for several devices

![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/30208898/ac4d1d24-978b-467a-84e9-d96aeba2074b)
