### ISSUE TITLE
Could you please make your customers life easy ??

### ISSUE THREAD

**Issue by jalmince** [Xinyuan-LilyGO/T-Display-S3#163]
1) I downloaded the last T-Display-S3 git repo. 

The Platformio.ini files are gone ?  why ?

2) as a work around, I put the Platformio.ini files back into the example/tft folder from the GIT I had  downloaded 2 month ago:

( I used to open the folder with vscode/plarformio and all was fine.)

but now inthe tft example the screen does not show anything after compile/upload ?

I might not be the sharpest in the toolbox, but I am really pi**sed off spending all my time fighting with the tools.., googling- up for possible solutions..., most of the time inadequate, while not having time left to enjoy creating iot things..

knid regards,
Jean-Pal

**Comment by lewisxhe** [comment]
Open the cloned repository directly with vscode instead of from the example folder
