### ISSUE TITLE
please add 16 keys on board

### ISSUE THREAD

**Issue by fab1an2** [Xinyuan-LilyGO/T-Display-S3#167]
Many project need menu or similar way to input data
 T-Display S3 have cpu and screen. Please add a old fasion T9 keyboard from phones. 0-9 and some other
summary 16 keys is very good options.

**Comment by teastainGit** [comment]
Check out this new LilyGO product:T-Decklilygo.ccCheers !TerryOn Jun 28, 2023, at 9:14 AM, fab1an2 ***@***.***> wrote:﻿
Many project need menu or similar way to input data
T-Display S3 have cpu and screen. Please add a old fasion T9 keyboard from phones. 0-9 and some other
summary 16 keys is very good options.

**Comment by srem1** [comment]
t-deck no have step up-down for 3.7V 1.5 V , 5V, 12 V etc.
no have lipo. 
in  my opinion S3 need more flexible power too, and keys out of the box. I no need whole keyboard, I need input small short text similar sms
