### ISSUE TITLE
Working example on ESP-IDF for text output

### ISSUE THREAD

**Issue by DimiG** [Xinyuan-LilyGO/T-Display-S3#169]
Maybe I'm writing in the wrong place, but I would really like to see a working example on ESP-IDF v5.1 for displaying text on the T-Display-S3 screen. The documentation is too fragmented, and there is no working example using the LVGL library anywhere on the Internet. Thank you.

**Comment by lauba11** [comment]
@DimiG  did you manage to achieve something on this topic?:)
