### ISSUE TITLE
factory example too large

### ISSUE THREAD

**Issue by csthiang** [Xinyuan-LilyGO/T-Display-S3#17]
I am having an issue uploading the factory example to the board, it is saying that the sketch is too big.

<img width="1281" alt="Screenshot 2022-10-06 at 2 16 32 PM" src="https://user-images.githubusercontent.com/1501828/194228881-528eb29c-7dc9-4c9c-9065-e932c2cdad12.png">

Am I missing any settings?

**Comment by tyeth** [comment]
In arduino I set the flash size to 8mb and partition to a larger app (3mb) and spiffs (1.5mb) size. Change the flash size. I admit I'm using arduino 1.8.3 not 2, and have my board set to ESP32 S3 Dev Module, cdc enabled.
