### ISSUE TITLE
Use a battery as power buffer

### ISSUE THREAD

**Issue by GitKalle** [Xinyuan-LilyGO/T-Display-S3#174]
Hello,

is it possible to use the board with a battery as power buffer? That means:

1) The board is powered by USB-C. A battery is connected on the JST-Connector. The program on board runs and the battery charges.
2) Power drops on USB-C and the board is powered by battery. The program on board runs continuously.
3) The power on USB-C came back and go on like point 1..

Thanks.

**Comment by lewisxhe** [comment]
During the switching process, it will restart. Cannot switch seamlessly
