### ISSUE TITLE
How to disassemble the display/acrylic?

### ISSUE THREAD

**Issue by AskAlice** [Xinyuan-LilyGO/T-Display-S3#176]
Trying to solder safely and I don't see any screws I can easily remove, is it possible to disassembly non-destructively ?

**Comment by teastainGit** [comment]
The display is taped down at each end and can easily be lifted, slowly incrementally, and judicious use of rubbing alcohol. I don’t recall if it electrically disconnects, but you can prop it out of the way to solder.Re-attach with fresh two sided tape.I use a sharp pointed soldering point and don’t usually move the display, just careful heating.Cheers !TerryOn Jul 27, 2023, at 9:48 AM, Alice Knag ***@***.***> wrote:﻿
Trying to solder safely and I don't see any screws I can easily remove, is it possible to disassembly non-destructively ?

**Comment by svdrummer** [comment]
You have screws on your board? What model do you have?
