### ISSUE TITLE
Factory Code for Basic T-Display S3

### ISSUE THREAD

**Issue by ZandrevdBerg** [Xinyuan-LilyGO/T-Display-S3#177]
What is the factory code or what do I need to change in the factory code for it to work with the basic version of the lilygo T-Display S3?

**Comment by teastainGit** [comment]
The factory code works fine with the LilyGO T-Display S3 if you edit in your router SSID and Password in the pinconfig.h!

**Comment by teastainGit** [comment]
Well, now it doesn't...
If I get it working again, I will post here!
-Terry
