### ISSUE TITLE
Whats the shame with pinouts?

### ISSUE THREAD

**Issue by Kabron287** [Xinyuan-LilyGO/T-Display-S3#179]
![Pins1](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/2493191/8a6e9659-fcb8-4f9c-8fe6-5d3d22000f92)
![Pins2](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/2493191/b1d93ff1-19da-43fb-9791-140f64643776)
Where's the truth?

**Comment by Kabron287** [comment]
Sorry I mixed up with T-Display

**Comment by teastainGit** [comment]
Hi, do you still have a question or should you close the issue?
Cheers, Terry



Cheers !
Terry Stainton

***@***.***

**Comment by Kabron287** [comment]
Sure. close it

**Comment by Kabron287** [comment]
yes
