### ISSUE TITLE
Arduino sketch upload baud rate "A fatal error occurred: Unable to verify flash chip connection"

### ISSUE THREAD

**Issue by davidhgriffiths** [Xinyuan-LilyGO/T-Display-S3#183]
On my mac (Apple silicon) I found I needed to drop the Arduino upload speed to 115200 otherwise I got a "A fatal error occurred: Unable to verify flash chip connection" error when I tried to upload a sketch.

**Comment by lewisxhe** [comment]
So now you can upload sketches with a baud rate of 115200?

**Comment by lewisxhe** [comment]
Have you tried [these](https://github.com/Xinyuan-LilyGO/T-Display-S3#faq) actions?
