### ISSUE TITLE
Can you provide a picture of the antenna section?

### ISSUE THREAD

**Issue by Arielhh** [Xinyuan-LilyGO/T-Display-S3#188]

**Comment by teastainGit** [comment]
Here is a iPhone pic of my LilyGO T-Display S3 .
<img width="496" alt="Screenshot 2023-09-20 at 12 47 39 PM" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/80008504/7d2f5c33-11a5-4847-8794-b0bd4722629b">
Are both the U.FL Ipex connector...AND...the built-in PCB 2D antenna connected to the ESP32?
It looks like you need to move the 0 Ohm resistor 90 deg,  from where it is shipped, to connect the U.FL Ipex connector.
On my LilyGO T-Display S3 boards there is no continuity from the ESP32 to the U.FL centre pin.
Many of us are asking for some clarity.
-Terry

**Comment by Arielhh** [comment]
I tried moving the o ohm resistor 90 degrees but same poor results with
various antennas that I purchased.
Also, I tried on a few lilygo youch units, and the same poor results
persist.

**Comment by sardonicsloth** [comment]
I would also like clarification here. Has anyone gotten the external ipex connector to work?

**Comment by JohnSkillman** [comment]
Still need info on this issue... Im having the same problem
