### ISSUE TITLE
Device not visible in device manager nor ls /dev/cu.*

### ISSUE THREAD

**Issue by robsannaa** [Xinyuan-LilyGO/T-Display-S3#193]
I am trying to install micropython on my T Display S3 but the device cannot be found. When I plug the device into my mac both the green and the reset led (red) are steady on. Any suggestions?

**Comment by teastainGit** [comment]
Some Macs prior to M1 needed the ch340 driver installed and the latest python revision, (to operate the Upload scripts, not necessarily your Python application).
Doing so may require sudo commands on the Mac Terminal.

Also, the device needs to enter download mode manually, holding GPIO 0 low while pressing and releasing the little black reset button and then bringing GPIO 0 back high.

you may also have to unplug the USB, in rare cases to get you Uploaded app to start running.
-Terry
