### ISSUE TITLE
Touch Gesture error

### ISSUE THREAD

**Issue by Brekel42** [Xinyuan-LilyGO/T-Display-S3#194]
Not sure if the version of the touch chip has changed, but the Gesture and Proximity registers are wrong for my board.
Register GES_ID_REG (0xD3) always reads 0x00, but I seem to be able to get gestures from the  PROXIMITY_ID_REG (0x01) as follows:

Swipe up/down  0x01 and 0x02 
Swipe left/right  0x03 and 0x04 (depending on screen rotation)
Long press 0x0C
Double click  0x05

**Comment by lewisxhe** [comment]
The gesture function seems to be only available on specific touch screen versions. As far as I know, there are two touch screens.
