### ISSUE TITLE
Is this the correct schematic for LilyGO T-Display S3 ?

### ISSUE THREAD

**Issue by teastainGit** [Xinyuan-LilyGO/T-Display-S3#197]
[SCH_T-Display-S3-MIDI_V1.1.pdf](https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/schematic/SCH_T-Display-S3-MIDI_V1.1.pdf)
(I found it here but it seems to be a MIDI model, not LilyGO T-Display S3 Touch)

Also do you have a schematic for LilyGO T-Display S3 Touch?
-Terry

**Comment by Llgok** [comment]
The schematic of the T-Display-S3 Touch is the same as the T-Display-S3

You can go to . /schematic/T_Display_S3.pdf to view the
