### ISSUE TITLE
How to work with the MIDI board?

### ISSUE THREAD

**Issue by d3mac123** [Xinyuan-LilyGO/T-Display-S3#198]
How to configure (and update the firmware) a S3 Midi board? When I connect my T-Display S3 to my PC, I see port COM5. However, when I attach the S3 board to the Midi board and connect it to the PC, port COM5 does not show up and nothing happens. What is the proper way to setup the board? There is no instructions on this git :(

**Comment by Llgok** [comment]
The Type-C port on the MIDI board will not be able to communicate and power the T-Display-S3 board until a program has been uploaded.

Did you connect the Type-C cable to the Type-C port on the MIDI board and the T-Display-S3 has not uploaded any program?

If so, please add the following code to the void setup() function to compile and upload the code once to the T-Display-S3 board and see if there are any serial ports left.

//Enable the 5V output of T-Display-S3.
pinMode(PIN_POWER_ON, OUTPUT).
digitalWrite(PIN_POWER_ON, HIGH).

Or upload the T-Display-S3-MIDI_V1.0.1_firmware.bin file.
