### ISSUE TITLE
Examples are throwing errors (but working fine). What is the reason for the error?

### ISSUE THREAD

**Issue by emmettprexus** [Xinyuan-LilyGO/T-Display-S3#199]
Using the LilyGo T-Display S3 and running the examples I can see it writes the following to the serial port:

```
[  1545][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected
E (1349) gpio: gpio_set_level(226): GPIO output gpio_num error
[  1546][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected
E (1355) gpio: gpio_set_level(226): GPIO output gpio_num error
```

This comes when calling the `tft.init()` method.

I have not been able to figure out what gpios it is talking about. Any way to fix this issue?

**Comment by lewisxhe** [comment]
I remember this was an error in TouchLib, it didn't check if rst was valid
