### ISSUE TITLE
How make rotation screen (Set portrait orientation)LVGL

### ISSUE THREAD

**Issue by rflras** [Xinyuan-LilyGO/T-Display-S3#20]
Hello! How can I rotate the screen? I need to set portrait orientation.

**Comment by LilyGO** [comment]
There are two methods: Method one is to modify the value in this parameter. Note that the width and height need to be modified in LVGL.
https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/ba0b273fba321a974c401e44d9f17d0c73e619e8/example/arduino/factory/factory.ino#L108

The second method is to use the built-in rotation of lvgl. Add the desired rotation direction here. https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/ba0b273fba321a974c401e44d9f17d0c73e619e8/example/arduino/factory/factory.ino#L133
