### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32-S3: No serial data received.

### ISSUE THREAD

**Issue by mesohn** [Xinyuan-LilyGO/T-Display-S3#201]
I tried. to reupload the firmware or code for the device.
It keeps stopping at this issue, I have no clue how to resolve it. 

![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/130438773/c2d41f14-ff75-4178-8dc7-21f209862475)

**Comment by pixelwave** [comment]
same problem

**Comment by lewisxhe** [comment]
The Readme FAQ has written the method to enter the download mode
