### ISSUE TITLE
Arduino_GFX example needs different constructor to work with current version of lib (1.4.2)

### ISSUE THREAD

**Issue by tomtobback** [Xinyuan-LilyGO/T-Display-S3#217]
Hi,
The [arduino_gfx_demo](https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/example/arduino_gfx_demo) example does not work with the latest Arduino_GFX version (1.4.2). It does work with version 1.3.0 included in your repo, but if you want to make it work with the latest, you will need to use a different constructor: `Arduino_ESP32PAR8` instead of `Arduino_ESP32LCD8` [here](https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/330baf44ad7bf04a1c74165c043a7d7a32f0f8d0/example/arduino_gfx_demo/arduino_gfx_demo.ino#L10C28-L10C45).

**Comment by lewisxhe** [comment]
Fixed
