### ISSUE TITLE
Arduino, only one partition scheme

### ISSUE THREAD

**Issue by pmanup** [Xinyuan-LilyGO/T-Display-S3#219]
![Captura de pantalla_2024-01-16_13-38-10](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/39590089/d095d842-e1e0-449a-9cf8-ce8f95558353)

**Comment by lewisxhe** [comment]
Variants are added by other customers, if you want more options, please use the ESP32 S3 Dev Module, as described in the README
