### ISSUE TITLE
I need to full of sdkconfig (esp-idf)

### ISSUE THREAD

**Issue by Shin-Chol-Choi** [Xinyuan-LilyGO/T-Display-S3#220]
I am using T-Display-S3 board. 
Use esp-idf as vs code. 
I need the correct sdkconfig file. 
It builds but doesn't work.
I've included some below.

# Automatically generated file. DO NOT EDIT.
# Espressif IoT Development Framework (ESP-IDF) 5.1.2 Project Configuration
#
CONFIG_SOC_MPU_MIN_REGION_SIZE=0x20000000
CONFIG_SOC_MPU_REGIONS_MAX_NUM=8
CONFIG_SOC_ADC_SUPPORTED=y
CONFIG_SOC_UART_SUPPORTED=y
CONFIG_SOC_PCNT_SUPPORTED=y
CONFIG_SOC_WIFI_SUPPORTED=y
CONFIG_SOC_TWAI_SUPPORTED=y
CONFIG_SOC_GDMA_SUPPORTED=y
CONFIG_SOC_GPTIMER_SUPPORTED=y
CONFIG_SOC_LCDCAM_SUPPORTED=y
CONFIG_SOC_MCPWM_SUPPORTED=y
CONFIG_SOC_DEDICATED_GPIO_SUPPORTED=y
CONFIG_SOC_CACHE_SUPPORT_WRAP=y
CONFIG_SOC_ULP_SUPPORTED=y
CONFIG_SOC_ULP_FSM_SUPPORTED=y
CONFIG_SOC_RISCV_COPROC_SUPPORTED=y

**Comment by lewisxhe** [comment]
Here is a simple example I made some time ago
https://github.com/Xinyuan-LilyGO/LilyGo-Display-IDF
