### ISSUE TITLE
Issue config pin SDA, SCL (use ESP-IDF)

### ISSUE THREAD

**Issue by tao-a-man** [Xinyuan-LilyGO/T-Display-S3#222]
hi @LilyGO team, I have a Issue: when i config pin like `#define LCD_TOUCH_SDA 17 #define LCD_TOUCH_SCL 18` Screen worked so good but Touch not worked, when i swap it `#define LCD_TOUCH_SDA 18 #define LCD_TOUCH_SCL 17` Sceen worked 20s so good after that it stop re-render, but Touch woked so good, Can I fix it?

**Comment by isthaison** [comment]
there is example https://github.com/OakDevices/ESP32-T-Display-S3-Slint-Cpp-Template/blob/master/main/src/hwInit.c#L36

**Comment by lewisxhe** [comment]
Here is a simple example I made some time ago
https://github.com/Xinyuan-LilyGO/LilyGo-Display-IDF
