### ISSUE TITLE
Low voltage on external lipo battery connected to the JST port

### ISSUE THREAD

**Issue by csthiang** [Xinyuan-LilyGO/T-Display-S3#223]
Board: t-display-s3 non-touch v1.2

I'm trying to power the board with a fully charged 3.7V lipo battery but it does not power on. I am aware of pulling pin 15 high for the display to work so I have the code bring up pin 15 and 38 for the screen. I've modified the `GetBatteryVoltage` demo code to add some sleep before powering the backlight on and it worked but I am seeing only 2.6-2.7v (Battery is at 4.18v as measured using multimeter). Measuring the 5v pin shows the same low voltage as well. Tried other known working li-ion it cannot work as well.

I have tried another of the same board and it is the same issue. There is no problem with using the usb-c to power the board. I have also updated the firmware but still seeing the same behaviour. 

What could be the problem? Faulty board (both???)?

**Comment by teastainGit** [comment]
If you are new to LilyGO T-Display S3 you might try reading through my self-help repository :
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples 
The ESP32 has a terrible ADC and it is not stable or particularly linear.
You 'updated the firmware'
What firmware did you update? I'm not sure what that means, the bootloader is in ROM, any sketch you may upload is also technically 'firmware'!
-cheers, -Terry

**Comment by Chihhao** [comment]
I encountered the same problem. Is there any solution?

**Comment by csthiang** [comment]
@Chihhao It appears that the fuse on my boards were broken, they should measure near 0ohms but were actually 350ohms. It appears to be a defect as I have 2 boards and both were broken.

You can try by testing the red circle (R10) to ground to see if you see battery voltage with a lithium battery or around 4.2V if you are using only USB. If you see less then 3V, it is likely broken. You can either replace it or just skip it by joining the green and red circle.

See image reference below.

<img width="371" height="473" alt="Image" src="https://github.com/user-attachments/assets/08d93fb8-fdfc-4a38-b2a0-b35c3cd48f5f" />
