### ISSUE TITLE
Cannot find i2c devices via stemma/qwicc port

### ISSUE THREAD

**Issue by jaymedavis** [Xinyuan-LilyGO/T-Display-S3#225]
I have tried 3 different devices via the stemma port for i2c.  Downloaded the example code from this repo, which scans sda 18 and scl 17.

What am I doing wrong?  output is "No I2C devices found"

edit:  I am using the esp32-s3 with the clear screen

**Comment by teastainGit** [comment]
The I2C JST Sh 1.0mm 4pin  port is SDA43, SCL44

<img width="1088" alt="T-DisplayS3_Pinout" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/80008504/8aed81e3-6884-4378-8118-8ab27527a106">

I presume that you have a LilyGO T-Display S3 non-touch screen and NOT the LilyGO T-Display S3 AMOLED?
The I2C is the same but I like to clear that up.
I have my own User Support GitHub repository here:
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples 
This may be some help for you!
The  'HotHead_temp_sensor'  example is I2C.
-Terry

**Comment by jaymedavis** [comment]
Awesome, thank you @teastainGit!  My I2C scanner is now finding my devices.  Starred/saved that repo as well!

**Comment by Jelle7and9** [comment]
In addition, standard SDA and SCL pins are 18 and 17, not 43 and 44 as suggested in de image above. 
Quick google search brought me here and I was misled by this. Figured it out after a while :-)
You have to define SDA_PIN 43 and SCL_PIN 44 otherwise the connector is not I2C.
