### ISSUE TITLE
wiring diagram issue PWR_EN

### ISSUE THREAD

**Issue by pvhoof** [Xinyuan-LilyGO/T-Display-S3#228]
I am trying to determine where I can safely connect external 5V (or if i need to 3.3V ) to the t-display s3 non touch so i can still use a USB cable to connect and program. I noticed the PWR_EN connected to D1 on the right side pf the wiring diagram. The only other place I found this is on pin 20 of the ESP. Is this the only thing it connects to? I would find this unlikely since pin 20 is connected to VDD3V3.

Second question I have: Is 5V input thru a Schottky diode on the battery connector safe as is suggested in another issue?

**Comment by lewisxhe** [comment]
Have you read this?

https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/205

There may be problems if external 3.3V access and USB are connected at the same time, because USB will also reduce the voltage to 3.3V for T-Display-S3
