### ISSUE TITLE
Upload yiedling errors when using upload_protocol = esp-builtin

### ISSUE THREAD

**Issue by dirk2947** [Xinyuan-LilyGO/T-Display-S3#234]
Hello there,

I'm not very knowledgeable regarding Microcontrollers so this issue isn't very in depth.
To tinker with my S3 without Touchscreen I followed the recommended platform.io guide.
Building of various demos works, uploading fails using the following default config:
**platformio.ini**
`upload_protocol = esp-builtin`

The error is as follows:
```
embedded:startup.tcl:26: Error: Can't find target/esp32s3-builtin.cfg
in procedure 'script'
at file "embedded:startup.tcl", line 26
*** [upload] Error 1
=========================================================================== [FAILED] Took 14.38 seconds ===========================================================================

Environment      Status    Duration
---------------  --------  ------------
Arduino_GFXDemo  FAILED    00:00:14.382
====================================================================== 1 failed, 0 succeeded in 00:00:14.382 ======================================================================
```

using the standard:
`upload_protocol = esptool`
works fine, took me a while to figure out though.

**Comment by lewisxhe** [comment]
The default has been changed to esptool, thank you
