### ISSUE TITLE
Incorrect pin number in schematic?

### ISSUE THREAD

**Issue by alandsidel** [Xinyuan-LilyGO/T-Display-S3#24]
The schematic shows the "boot" button connected to pin 32 / GPIO0 and the "Key" button connected to pin 11 / IO35 with a 100k pull-up.  The pin numbers don't correspond to the pin numbers on the ESP32-S3 so I don't know what they're in reference to.

GPIO0 does work for using the boot button, but GPIO35 does not seem to work for using the other button.

Is 35 the correct pin to use that button?  My PCBs are marked V1.2 on the silk screen.

**Comment by LilyGO** [comment]
I didn't find the schematic to be questionable. Are you asking the wrong board. If you insist, please attach a picture.

**Comment by alandsidel** [comment]
> I didn't find the schematic to be questionable. Are you asking the wrong board. If you insist, please attach a picture.

What do you need a picture of?

**Comment by LilyGO** [comment]
You think the wrong picture.
