### ISSUE TITLE
ESP32 v3.0.0-rc1

### ISSUE THREAD

**Issue by chipko** [Xinyuan-LilyGO/T-Display-S3#240]
In older documentation, it has stated that ESP32 board version should be below v3.0.0 - is this now revised since ESP32 has gone into Release Canidate 1?

**Comment by teastainGit** [comment]
Just an other User here: 
Arduino IDE only provides 2.0.15 and all my boards work 100%.
If you are using IDF or Platformio why not try compiling with 3.0.0 Release Canidate 1(sic), and see if anything is broken?
