### ISSUE TITLE
TFT communicate through SPI or gpio 8bit parallel?

### ISSUE THREAD

**Issue by 08822407d** [Xinyuan-LilyGO/T-Display-S3#241]
I'd like to know about whether can my program control or send data to TFT screen through SPI.
I'm a greenhand on embedded, forgive my low ability getting information from datasheet or from other material.

I'm working on a oscilloscope program. Now I found that max rate of refreshing screen by Bodmer's TFT_eSPI lib in a task limited to 15FPS. Then I trace function calling stack and found with this board's configure, the library finally write data through gpio. I asked an embedded practitioner with this piece of code and the pin map on product web page, he said that the board seems send data in 8bit parallel mode through gpio.

**Comment by teastainGit** [comment]
Well, an oscilloscope program will be very challenging on an ESP32. Usually Oscilloscopes use a dedicated ASIC mixed signal proprietary chip for the signal processing.
Your max horizontal sweep rate will be low, possibly just a digital capture and display device.
I can get 60 fps with the DMA style technique of only sending the the portion of the screen that has changed, not a complete re-fresh.
This will be an advanced app, you cannot let your PC or Linux experience allow you to use multiple helper apps, it's almost Assembly Language at this point. Remember with embedded there is no low level operating system, just your C code compiled to binary!
