### ISSUE TITLE
USB and schematics

### ISSUE THREAD

**Issue by felix-max** [Xinyuan-LilyGO/T-Display-S3#245]
It seems that USB connector and circuitry is missing in schematic. Also on PDF posted some days ago as reply at [issue #236](url=https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/236) doesn't have it

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/22990954/cf737b27-72f8-4d9b-9c06-64cb588850fc)

**Comment by felix-max** [comment]
Thank you @lewisxhe . My fault I didn't realize it was the connector and not a charger chip.
Thanks
