### ISSUE TITLE
32 Bit Shares

### ISSUE THREAD

**Issue by 777Canned** [Xinyuan-LilyGO/T-Display-S3#246]
I began using my Lilygo about 1 month ago.  
In the beginning, the number of 32 bit shares was 0.  The number keeps going up.  It is now showing 15 32 Bit shares.  Is it a good thing that the number of 32 bit shares keep increasing?

**Comment by teastainGit** [comment]
Are you mining?

**Comment by 777Canned** [comment]
Yes, mining.

**Comment by teastainGit** [comment]
Then, the 32 bit mining shares are not a LilyGO problem.
You should search for the mining site that you use and ask there.

**Comment by teastainGit** [comment]
Lewis xe please close!
