### ISSUE TITLE
New T-Display S3 - WIFI 5G not working

### ISSUE THREAD

**Issue by Spirarementum** [Xinyuan-LilyGO/T-Display-S3#250]
Hello,
Just bought 2 x T-Display S3... using a simple Internet Clock Sketch I was able to connect only to my 2.4 GHz Acces Point.
Connecting to a 5GHz Access Point is not working.
Does it support 5GHz WIFI ?
What are the 5GHz WIFI specifications?
Thank you

**Comment by teastainGit** [comment]
Espressif ESP32 S3 does not support 5GHz.
