### ISSUE TITLE
Query regarding voltage input at C-port  (VERSION_20200811)

### ISSUE THREAD

**Issue by farishgithub** [Xinyuan-LilyGO/T-Display-S3#252]
Hi,

I have bought some Tcall SIM800l modules of VERSION_20200811 for my IoT project. I have a question regarding the max voltage that I can give on its USB port safely as I am planning to connect it directly to battery via its USB C port.  Can I give say 8 V at the USB C port ? Further, could anyone plz share its datasheet if possible as I am not able to find it on their website.

Thanks.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/22990954/a6527612-013e-458a-9325-a1be46eda3ed)


The safest operating voltage is 5V
