### ISSUE TITLE
Detecting charging state

### ISSUE THREAD

**Issue by jperrela** [Xinyuan-LilyGO/T-Display-S3#254]
Hi,

I'd like to detect whether the battery is charging or not, how can I do it? I can't find a pin connected to VBUS to read its state.
The method of the battery example only helps to detect if the battery is present or not.

Thanks!

**Comment by lewisxhe** [comment]
The battery voltage can be detected. If it is greater than 4.2V, it can be determined that the USB is connected, but it cannot be determined whether it is charging. The charging indicator can only be checked for charging.
