### ISSUE TITLE
Using the PCBDesignClock example compiles but there is not enough memory on device to run?

### ISSUE THREAD

**Issue by fromutome** [Xinyuan-LilyGO/T-Display-S3#256]
The example code PCBDesignClock compiles with Arduino IDE but after that the erro below say that program memory space is to large. I have not changed anything in the code.

Are there LilyGO T-display S3 devices with different size of memory?
Am using the LilyGO T-Display S3 in the board selection in the Ardiono IDE.
When using the board info function in arduino it says it's a ESP32-S3 Box?

Best Regards
//Johan

Sketch uses 3147449 bytes (100%) of program storage space. Maximum is 3145728 bytes.
Global variables use 47104 bytes (14%) of dynamic memory, leaving 280576 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board

**Comment by fromutome** [comment]
Thanks for the suggestion but that partition scheme is not availble on my installation/configuration.
How can I enable this option?

**Comment by teastainGit** [comment]
They have screwed up with their new board def! 
Use ESP32S3 Dev Module board def and select 
Partition Scheme: "Huge APP (3MB No OTA/1MB SPIFFS)

<img width="932" alt="Screenshot 2024-06-04 at 3 56 58 PM" src="https://github.com/Xinyuan-LilyGO/T-Display-S3/assets/80008504/ff7bfe78-4ec2-454b-88d5-65cdeade55f5">

**Comment by fromutome** [comment]
Thanks! that solved the issue :)

**Comment by akshayamytaneja** [comment]
![Screenshot 2024-07-15 092813](https://github.com/user-attachments/assets/bd12a58f-32d0-489d-92a2-0b7a6b3e086f)

Facing the same problem.
Using a T-Display S3 (no touch)

Upload procedure: Hold down BOOT button, press and release Reset, let go of the BOOT button (has worked for other examples)

**Comment by teastainGit** [comment]
What 'ESP32 by Espressif' board def revision are you using?

**Comment by whzbngry** [comment]
I think I haven't upgraded from 2.0.16 since it breaks my other projects.
![Screenshot 2024-07-15 095009](https://github.com/user-attachments/assets/59ac6403-e1be-4ca4-860d-bc4a6b59be83)

**Comment by teastainGit** [comment]
VOLOS! The guy is a genius, but he assumes we all are!
I had to watch his video frame by frame to learn the correct settings.
<img width="909" alt="Screenshot 2024-07-15 at 12 30 58 PM" src="https://github.com/user-attachments/assets/38b4d1ea-3d85-4f62-b892-759eec8cb54a">
8MB and 8MB with SPIFFS
I use ESP32 ver 2.0.15, just my habit for now.
Cool app though!
-Terry

**Comment by whzbngry** [comment]
Thanks a lot @teastainGit !
I got it working with the following settings with 2.0.16 esp32 by Espressif.

![Screenshot 2024-07-15 105258](https://github.com/user-attachments/assets/e8974b28-fc0e-49a7-8089-8094324b4771)
