### ISSUE TITLE
Detecting USB Power 

### ISSUE THREAD

**Issue by Arielhh** [Xinyuan-LilyGO/T-Display-S3#260]
Hi,
When working with the battery,  Is there a way to detect,  using code only, when a usb power is connected (not using external components or connecting any additional cables)?

Thx

**Comment by teastainGit** [comment]
You could monitor the battery voltage (with the pin 4 ADC) which is nominally 3.3 to 4.2 and when it jumps to 5V, you know that USB is connected.

**Comment by Arielhh** [comment]
Many thanks, it's a good idea, this is exactly what i was trying to do right now :)

**Comment by Arielhh** [comment]
It didnt work as the TP4065 is not allowing the voltage to change on the battery terminals when the USB cable is connected.
