### ISSUE TITLE
ESP version 3.0.2

### ISSUE THREAD

**Issue by salasidis** [Xinyuan-LilyGO/T-Display-S3#263]
Any compatibility issue upgrading the Arduino board manager to 3.0.2 from 2.0.11.

I am using the T-Display S3 AMOLED.

Thanks.

**Comment by teastainGit** [comment]
Yes, ESP32 Espressif boards ver 3.x.x is broken right now. LilyGo suggest using ver2 board defs, I use 2.0.15 with success.

PLUS this is the LilyGO T-Display S3  ***non AMOLED***  support page!
-cheers
