### ISSUE TITLE
Lilygo T-Display S3 Touch - Unable to mount filesystem

### ISSUE THREAD

**Issue by nelslar42** [Xinyuan-LilyGO/T-Display-S3#265]
For the life of me I cannot get this device to upload files to the filesystem.

i have an HTML in my projectroot/data=index.html

and i have properly defined littlefs in my platformio.ini

anyone have this issue?? help please!

**Comment by lewisxhe** [comment]
Did you upload the filesystem? And did you choose the litefs partition table correctly?
