### ISSUE TITLE
T-DISPLAY-S3 PlatformIO and framework ESP-IDF monitor doesn't work

### ISSUE THREAD

**Issue by BullT** [Xinyuan-LilyGO/T-Display-S3#266]
Hi,

I'm using the LILYGO T-DISPLAY-S3 with PlatformIO and framework ESP-IDF.

When I upload and monitor, the monitor doesn't work.

Do you know why?

![image](https://github.com/user-attachments/assets/13162788-3005-489e-9208-aed9e2eeb89d)

**Comment by teastainGit** [comment]
Did you 'Enable' USB CDC on Boot?

**Comment by BullT** [comment]
Hi,

I don't know how do it :)

**Comment by teastainGit** [comment]
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

**Comment by BullT** [comment]
Hi and thank you,

But it doesn't work.
I'm using framework ESP-IDF not Arduino.

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/5ff5a439-53cd-4c7d-a9bf-cf99e5164c47">

**Comment by BullT** [comment]
Hi,

I'm going to move it.

Thank you

**Comment by BullT** [comment]
Hi,

I found the concern.
It was on menuconfing, I had selected Default: UART0, after change to USB CDC it start to works:

<img width="420" alt="image" src="https://github.com/user-attachments/assets/7434df13-869e-4fab-9f6b-3bfae5e4781f">

**Comment by teastainGit** [comment]
Very good news, thanks for getting back, I will add it to my experience.
