### ISSUE TITLE
External antenna

### ISSUE THREAD

**Issue by imoiseev** [Xinyuan-LilyGO/T-Display-S3#267]
Has anyone had any success using an external antenna?

I re-soldered the capacitor at 90 degrees. I connected two types of antennas, but I see almost no difference in the RSSI parameter.

Maybe something else is needed? Please share any information

**Comment by isthaison** [comment]
It's not actually connected yet 
![image](https://github.com/user-attachments/assets/2140ffcd-1ddb-47bd-a698-faaebcfa15f5)
