### ISSUE TITLE
How to make it as an arduino IDE library

### ISSUE THREAD

**Issue by happy77fr** [Xinyuan-LilyGO/T-Display-S3#268]
Hello,

I would like to access the examples natively inside Arduino IDE by importing this directory as a ZIP.
Would it be possible to add the necessary files like library.properties in the main directory?

Thank you

**Comment by teastainGit** [comment]
You can just go to the front page of the repository and download the .zip.
https://github.com/Xinyuan-LilyGO/T-Display-S3
The green button marked Code.
Choose 'Download Zip.
On your desktop, expand the contents and move the contents to your Arduino IDE library folder....and Done!
