### ISSUE TITLE
T-Display-S3 Flip Clock Sample

### ISSUE THREAD

**Issue by oldbug62** [Xinyuan-LilyGO/T-Display-S3#273]
Hello,

Is it possible to simply rotate the screen 180 degrees in the program?

**Comment by lewisxhe** [comment]
```
Range: 0 ~ 3
 tft.setRotation(1);
```

**Comment by oldbug62** [comment]
@lewisxhe 

thanks for your answer where exactly do i have to insert it and how should it be configured?

/* LCD CONFIG */

#define EXAMPLE_LCD_PIXEL_CLOCK_HZ (6528000) //(10 * 1000 * 1000)

// The pixel number in horizontal and vertical

#define EXAMPLE_LCD_H_RES 320

#define EXAMPLE_LCD_V_RES 170

#define LVGL_LCD_BUF_SIZE (EXAMPLE_LCD_H_RES * EXAMPLE_LCD_V_RES)

#define EXAMPLE_PSRAM_DATA_ALIGNMENT 64

#define Range: 0 ~ 3

#define tft.setRotation(0);

**Comment by lewisxhe** [comment]
After tft.init()
