### ISSUE TITLE
reboot at wifi

### ISSUE THREAD

**Issue by ericgrand** [Xinyuan-LilyGO/T-Display-S3#275]
My T display S3 has started to develop a bug. As soon as it connect to wifi, it reboots. I have reuploaded my sketch with no improvement.
I have used the flash tool and the firmware available on the github and same behaviour, I have the Lilygo logo, then scan wifi and it reboots.
Same behaviour on various USB cable and power source...
I suppose it is a harware issue?

Thanks for your support!

Eric

**Comment by lewisxhe** [comment]
If it restarts when connected to wifi, please replace the data cable and power supply for testing. Test it under several power supplies. If the same result is obtained, it can be determined that there is a problem with the PCB power supply.

**Comment by ericgrand** [comment]
Ok, so it is a defective PCB. It has been tested with different cables, power sources and even with external battery through the battery port.
Is there any warranty on this item? It is less than 18 months old.

**Comment by lewisxhe** [comment]
I don't know if there is a warranty, you need to ask where you bought it
