### ISSUE TITLE
Serial Monitor not Working in Platformio

### ISSUE THREAD

**Issue by Dutu06** [Xinyuan-LilyGO/T-Display-S3#276]
I have checked the serial port in the main.cpp and it's correct but the monitor still says only
 --- Terminal on COM4 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H

The code in platform.io:
[platformio]
default_envs = twatch-s3
boards_dir = ./board/LilyGoWatch-S3

[env]
lib_extra_dirs = .
upload_speed =  921600
monitor_speed = 115200
board_build.filesystem = fatfs
board_build.partitions = app3M_fat9M_16MB.csv

[env:twatch-s3]
platform = espressif32@6.3.0
framework = arduino
board = LilyGoWatch-S3
build_flags = -DARDUINO_USB_MODE=1
             -DARDUINO_USB_CDC_ON_BOOT=1

**Comment by lewisxhe** [comment]
Are you using T-WatchS3? This is T-Display-S3
