### ISSUE TITLE
Missing SCLK and MOSI pins for LCD

### ISSUE THREAD

**Issue by Mehdow** [Xinyuan-LilyGO/T-Display-S3#277]
Hi, I'm having a hard time finding which are the pins for SCLK and MOSI for the LCD Screen in this board, as I've been using Adafruit ST7789 library until now and it needs them.

In the T-Display model (1.14'' screen) there's an image where they're specified, but in this T-Display-S3 the image shows a lot of pins for the LCD but none of those. I've tried using "WR" and "RD" without any success, as nothing is being shown in the screen for this library.

**Comment by lewisxhe** [comment]
This is a parallel interface, not an SPI interface.

**Comment by Mehdow** [comment]
I see, I'll use TFT_eSPI then. Thanks for the clarification!
