### ISSUE TITLE
Lilygo T-Display no longer visible as usb device

### ISSUE THREAD

**Issue by guggu1** [Xinyuan-LilyGO/T-Display-S3#282]
Since I have unsuccessfully flashed the display, it is no longer shown as an usb device neither on a Mac laptop nor  a raspberry pi 4. 

Also, I cannot find a button named „boot“ which seems to be necessary to reset the device to its factory settings. 

Photograph of the board

![image](https://github.com/user-attachments/assets/9e3176a2-f4ed-4d45-80e6-e5e986dd35b4)
![image](https://github.com/user-attachments/assets/8a390adb-01ba-40de-8ef9-dbf6ee9abe8f)

thanks 

ccs

**Comment by pjeantaud** [comment]
Hello,

The boot button should be on the right of the USB connector and the reset one on the lower side at left when the USB is seen on the upper side.

Regards,

Patrick
