### ISSUE TITLE
how to power from 3s battery

### ISSUE THREAD

**Issue by COLVERTYETY** [Xinyuan-LilyGO/T-Display-S3#29]
Hello,

I am wondering what the proper way to power this board is.
I have a 3s battery that I regulate to 5v with an lm7805 and am wondering how to properly power the board without getting a conflict when the USB is plugged in and delivering power.

Is a diode between my lm7805 and the 5v of the board enough? 

Thank you for your response.

**Comment by LilyGO** [comment]
There is a 2Pin connector on the back of the USB. You can directly connect to 3.7V lithium battery or polymer battery.
