### ISSUE TITLE
Core debug level setting in English

### ISSUE THREAD

**Issue by HowdyMoto** [Xinyuan-LilyGO/T-Display-S3#30]
Hello,

You instructions are clear, except the core debug level is shown with what looks like a Chinese character that is hard to translate. Can you add the setting in English?

**Comment by HowdyMoto** [comment]
Go to https://github.com/Xinyuan-LilyGO/T-Display-S3
Under "Quick Start" there is a list of settings. 
The "core debug level" setting is a Chinese character.

Thanks!

**Comment by LilyGO** [comment]
I'm sorry that this character bothers you. I reproduced this interface here.
![image](https://user-images.githubusercontent.com/31160602/197915063-61c6ff88-3950-43ad-abac-bfab47a28663.png)
