### ISSUE TITLE
Example TFT results in blank screen

### ISSUE THREAD

**Issue by roblatour** [Xinyuan-LilyGO/T-Display-S3#35]
The example found here:   https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/example/tft
is suppose to display information on the  screen of the T-Display-S3.

However, while the example compiles, when it is run it results in a blank screen - that is to say no output is displayed on the screen of the T-Display-S3.

Also, the file https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/example/tft/pin_config.h
has these two lines:
   #define WIFI_SSID                             "xinyuandianzi" 
   #define WIFI_PASSWORLD               "AA15994823428"

which are not used by the tft example - as the tft example does not have code to make a wifi connection.

The example at:
https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/example/factory
works fine.

**Comment by LilyGO** [comment]
Please use the tft library provided by us. There will be changes here.

**Comment by roblatour** [comment]
I did use the tft library provided by you - and as noted above the other example (factory) works fine.

However, I raised this issue because the tft example did not work for me.  

As far as I can see there have not been any coding changes to resolve this, so I'm not sure why this issue is closed?

**Comment by LilyGO** [comment]
Are you using the Arduino IDE (Arduino 2.0.0). This version will automatically update the library version. This will overwrite the files you have dragged into the \Arduino\libraries directory. So cause your use of tft routines will fail. You can switch to Arduino 1.8.1x version and it will be solved.

**Comment by roblatour** [comment]
actually, having your libraries where they are 
...  Arduino\libraries\TFT_eSPI
is working fine for the factory example as well as another program I am writing.
Have you tried the tft example lately?  Is it working for you?

**Comment by LilyGO** [comment]
Everything works fine for me with this library, you can try it with Arduino version 1.8.19 (re-override the TFT library)

**Comment by roblatour** [comment]
yes, its working now with arduino 2.0.1 ; not sure what the problem was but I'm sure it was on my end - sorry about that.
