### ISSUE TITLE
Do you have 3D file of board with screen attached?

### ISSUE THREAD

**Issue by t-rekttt** [Xinyuan-LilyGO/T-Display-S3#36]
I downloaded and opened your 3D file but there was only the ESP32S3 board and no screen, hence it's difficult for me to design a case for it. It would be great if you can provide 3D file with screen included.

**Comment by tyeth** [comment]
@mmMicky is it possible to get both the screen versions as 3d files. The rectangular non-touch version, and the newer touch version with rounded glass. Thanks!

**Comment by mmMicky** [comment]
https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/3D_file/glass_screen.stp

I uploaded the screen file. actually using the need to combine them together

**Comment by t-rekttt** [comment]
> https://github.com/Xinyuan-LilyGO/T-Display-S3/blob/main/3D_file/glass_screen.stp
> 
> I uploaded the screen file. actually using the need to combine them together

I'm having this problem when trying to import the file into Autodesk Fusion 360. Please check.
![Screenshot_16](https://user-images.githubusercontent.com/9071846/206985600-04a804ce-910b-4907-96c8-c19329301701.png)

**Comment by mmMicky** [comment]
I use Rhino 7 to open fine.

**Comment by tyeth** [comment]
Thanks @mmMickey, that's brilliant.
@t-rekttt thanks for the warning, it opens with freecad (file->import)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/6692083/207051907-8d0916b5-e30b-4dbf-b79d-68c7858d06e8.png">

**Comment by tyeth** [comment]
[TDisplayS3touch_stl_fbx_step.zip](https://github.com/Xinyuan-LilyGO/T-Display-S3/files/10220939/TDisplayS3touch_stl_fbx_step.zip)
Added version together, it's approximately positioned 1.5mm from top edge and 5.5mm from board to glass surround which matches roughly the unit in my hands, and matches the normal t-displays3 if you measure to the top of LCD.
![Screenshot 2022-12-13 at 18 17 36](https://user-images.githubusercontent.com/6692083/207413376-e86a1f40-075b-4b2c-9783-9387a9267ac9.png)
