### ISSUE TITLE
Usb port disappears

### ISSUE THREAD

**Issue by SoniaZotz** [Xinyuan-LilyGO/T-Display-S3#38]
on reset of the board  - USB Serial Port Com4 shows up 

couple second-later it disappears 

cannot load the  ESP

**Comment by SoniaZotz** [comment]
it is running ...  **How do I stop it ??**

/* Hello World Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"

void app_main(void)
{
    printf("Hello world!\n");

    /* Print chip information */
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    printf("This is %s chip with %d CPU core(s), WiFi%s%s, ",
            CONFIG_IDF_TARGET,
            chip_info.cores,
            (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
            (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");

    printf("silicon revision %d, ", chip_info.revision);

    printf("%dMB %s flash\n", spi_flash_get_chip_size() / (1024 * 1024),
            (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");

    printf("Minimum free heap size: %d bytes\n", esp_get_minimum_free_heap_size());

    for (int i = 10; i >= 0; i--) {
        printf("Restarting in %d seconds...\n", i);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
    printf("Restarting now.\n");
    fflush(stdout);
    esp_restart();
}

**Comment by LilyGO** [comment]
USB CDC is also a task for ESP32. It restarts or resets to re-enumerate.

**Comment by SoniaZotz** [comment]
but I'm in a lockup system - cannot access the USB port because the system is constantly **rebooting**  as shown in the program above  

how do I **break out of this program** if my USB is constantly being reset USB CDC is also a task for ESP32. as you say ...**.it restarts or resets to re-enumerate.**

**Comment by SoniaZotz** [comment]
![image](https://user-images.githubusercontent.com/10633874/199316777-9fa9066a-7e6c-42c5-bd2c-0b05390bdc7c.png)
![image](https://user-images.githubusercontent.com/10633874/199316841-503404a4-96cf-4408-a1a2-d9cf19e4d895.png)

**Comment by LilyGO** [comment]
Press and hold the BOOT button, then short press the reset button, and then release the BOOT button to enter the BOOTLOADER mode.

**Comment by SoniaZotz** [comment]
**### Thank you**

![image](https://user-images.githubusercontent.com/10633874/199406105-eec61c61-052a-474f-af29-0e8ba9891e7c.png)
