### ISSUE TITLE
documentation on external antenna

### ISSUE THREAD

**Issue by roblatour** [Xinyuan-LilyGO/T-Display-S3#39]
Missing documentation on external antenna.

Is it ok to use the t-display without an external antenna attached?

Other than plugging in an external antenna do you have to do anything to use it?  For example, setting a jumper?

**Comment by LilyGO** [comment]
It can use the onboard antenna. The jumper is only necessary when you need to use an external antenna.

**Comment by roblatour** [comment]
where is the jumper on the board? ( a photo would be helpful )

**Comment by achtnullzwei** [comment]
I am interested as well. Wouldnbe great if it can be documented how to set the bosrd up for external antenna usage.

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/200214589-dbfab2a4-1ade-4be0-9858-f06d5db0aa7a.png)
Switching to external requires rotating this resistor 90 degrees.
