### ISSUE TITLE
Voltage and power of signal outputs

### ISSUE THREAD

**Issue by SimLV** [Xinyuan-LilyGO/T-Display-S3#40]
Could you please put which voltage it could send on signal outputs and which load is acceptable on main page?

**Comment by mmMicky** [comment]
I don't understand you

**Comment by SimLV** [comment]
Excuse me.
I mean how much voltage I may drain from signal outputs. 
How much voltage I may put into signal inputs (are they 5V or 3.3V?).
and how many milliamps without risk of damage to the board.

I.e. from SoC datasheet
![image](https://user-images.githubusercontent.com/68837817/201011505-b92a87ba-621b-4502-a1d7-dc9e2370d7ea.png)

![image](https://user-images.githubusercontent.com/68837817/201011627-578a1030-00c0-490b-b37f-e28136a5239f.png)

**Comment by mmMicky** [comment]
The circuit signal needs a 3.3V voltage, which can ensure that the circuit board will not be burned and work normally.
