### ISSUE TITLE
LilyGo T-Display S3 shows as USB JTAG/serial debug unit in windows device manager and no code can be uploaded

### ISSUE THREAD

**Issue by AquaCobell** [Xinyuan-LilyGO/T-Display-S3#50]
![image](https://user-images.githubusercontent.com/71768923/202865309-89e8b90a-55c9-4b83-8fa0-a6b349415440.png)

Whenever I try to upload some code via Arduino IDE it shows me the following error 
![image](https://user-images.githubusercontent.com/71768923/202865337-a4ec460a-1c74-435c-93ae-597382635ff0.png)

![image](https://user-images.githubusercontent.com/71768923/202865352-43a7b484-c44b-47ae-bbba-13ddd6f89627.png)

**Comment by mmMicky** [comment]
I suggest you enter download mode and then upload. The operation is to press and hold the BOOT button and then connect the USB when the power is off. After the upload is complete, click the reset button to run the user code.
