### ISSUE TITLE
ESPHome support

### ISSUE THREAD

**Issue by OXOTHuK1976** [Xinyuan-LilyGO/T-Display-S3#52]
It is possible to support ESPHome with this device/display?

**Comment by mmMicky** [comment]
Not sure if the screen supports it.

**Comment by OXOTHuK1976** [comment]
Screen itself can be used in esphome with external library with your patch.   
example: https://github.com/landonr/lilygo-tdisplays3-esphome

but will be great to have native esphome support.

**Comment by Jason2866** [comment]
Or use Tasmota ;-) Fully supported.

**Comment by eisaheinig** [comment]
> Or use Tasmota ;-) Fully supported.

i was not able to find it on this list: https://templates.blakadder.com/esp32.html

**Comment by Jason2866** [comment]
@eisaheinig Yeah, missing there. Needs adding...
Install from here https://tasmota.github.io/install/ using this build
![0C4405AC-1A6E-4DBD-B919-3D610C416963](https://user-images.githubusercontent.com/24528715/214587139-49d61e66-5821-46b6-87cd-ec21b6fabeb2.jpeg)
and configure it via Tasmota Menu Autoconfig. There it is.

**Comment by lewisxhe** [comment]
If you still have problems, please open it again
