### ISSUE TITLE
File T-Display-S3-main Not unzipping correctly

### ISSUE THREAD

**Issue by GerryGit** [Xinyuan-LilyGO/T-Display-S3#56]
When unzipping the file the following messages are displayed, and the files are not all extracted:
C:\Users\I-7\Downloads\T-Display-S3-main.zip
Unexpected end of data
Data error : T-Display-S3-main\doc\esp32-s3_technical_reference_manual_en.pdf

**Comment by mmMicky** [comment]
Maybe it's a network problem. Please download again.

**Comment by GerryGit** [comment]
Thank you, it worked today.
