### ISSUE TITLE
are there I2C pins for this board?

### ISSUE THREAD

**Issue by contractorwolf** [Xinyuan-LilyGO/T-Display-S3#58]

**Comment by tyeth** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/6692083/205455209-960482b6-4ce2-490d-b11f-da21999ac854.png">
43+44 as attached to the quIIC connector
The [qwiic ](https://www.sparkfun.com/qwiic) connector, also referred to as stemma QT or JST-SH 1.25mm, will give you easiest use of i2c, but the pins are broken out too.
You can always check the schematics for such things, but also the pinout diagram for other lilygo boards is more informative, so fair question

**Comment by teastainGit** [comment]
mmicky, please close. It looks like OP bailed on his question, or it was answered by tyeth

**Comment by contractorwolf** [comment]
Ok I see it now, thanks for the advice.  might want to add the standard SDA and SCL markings to the pin diagram.  I didnt know CLK_OUT and CLK_OUT2 would indicate I2C.  Thanks!

**Comment by tyeth** [comment]
To be fair the pinout diagram is missing some of the more useful extra pin function labels, like I2C, which is why the question was asked. Maybe it can be updated to be better, more like the T-Sim7000G which at least highlights i2c
<img width="622" alt="image" src="https://user-images.githubusercontent.com/6692083/205501576-6404e0d3-d1df-440f-9ffa-66fbeef4e7ff.png">

**Comment by mmMicky** [comment]
ESP32 32 can map any peripheral to any gpio (except USB). I will close this question.

**Comment by tyeth** [comment]
I disagree, although the mux supports remapping, not every pin to every function. Make life easier for people and include helpful info, it's not about what can be done, but _what pins are the default_ for example if Wire.begin was called (and you have an IIC/I2C/qwiic connector for the purpose so it's defined although remappable).

 It's new users you're helping, veterans will waste their time in datasheets and framework sourcecode or already know about remuxing.

**Comment by marshalleq** [comment]
I just came here due to the same problem with lilygo s3 v 1.2 lora device.  I'm still not sure what to connect to to be honest.  While you technically can connect to most pins, the software I've got is not configurable.  Some labels would sure be helpful.
