### ISSUE TITLE
Poor WiFi function

### ISSUE THREAD

**Issue by teastainGit** [Xinyuan-LilyGO/T-Display-S3#67]
I do a lot with ESP_NOW and found my two T-Displays S3s to have very poor RF performance, compared to M5Stack units.
I am also seeing unanswered complaints over on the LilyGO community about poor WiFi.
Someone even added an external antenna with no improvement.
A) Is there some guidance, advice for us to use WiFi?
B) Is there a driver or demo sketch available to help test?
-Cheers, Terry

**Comment by mmMicky** [comment]
The RF signal is also modulated, maybe the gain of the onboard antenna is relatively weak. It is expected that the antenna scheme will be changed in the next version.
