### ISSUE TITLE
Examples Dabble Issue

### ISSUE THREAD

**Issue by buzzysale** [Xinyuan-LilyGO/T-Display-S3#68]
In the examples, particularly the NES example, the dabble app connects to ble, but does not download the pin configuration.  
"Connected". "Acquiring connected board detail" 
and then nothing happens and no detail is provided.

**Comment by mmMicky** [comment]
I use Android. I can use it directly after connecting to bluetooth, there is no other prompt.

**Comment by buzzysale** [comment]
How do I troubleshoot what's happening?

**Comment by mmMicky** [comment]
I am also using platformIO to build. You try to upload an NES game to the data directory. Then upload to the file system to see if it is running normally.

**Comment by mmMicky** [comment]
The sample doesn't have any NES games built in. Because uploading it data infringement. I can only provide methods used by the simulator.

**Comment by buzzysale** [comment]
Uploading a rom is successful. That part works. I

t’s dabble that isn’t working with the esp.

**Comment by mmMicky** [comment]
There is also a stupid but effective way. It is recommended that you find a mobile phone with Android system for testing.

**Comment by buzzysale** [comment]
Okay and if that works?

**Comment by mmMicky** [comment]
If it works fine, it proves that dabble software is not compatible to work on iphone.
