### ISSUE TITLE
How to convert images to C array ?

### ISSUE THREAD

**Issue by tavdog** [Xinyuan-LilyGO/T-Display-S3#84]
I've been trying everything and I can't get proper colors.  The color is always shifted one way or the other. see photo.
Is there a walkthrough somehwhere on how to do this ?  The tool in the TFT_eSPI doesn't work.  I can get recognisable images by exporting from GIMP as PNG and using img2cpp utility to create the C-array, but the colors are never correct.
<img width="490" alt="Screen Shot 2023-01-13 at 1 54 37 AM" src="https://user-images.githubusercontent.com/8324295/212314738-86270bde-2169-4a4b-85de-dac3086d5f1a.png">

**Comment by tavdog** [comment]
I have tried the instruction in this repo but no matter what Blue and Red are swapped.
<img width="863" alt="Screen Shot 2023-01-13 at 1 22 51 PM" src="https://user-images.githubusercontent.com/8324295/212436507-f43c9d06-ebd3-42d4-88a4-250b30f2578a.png">

**Comment by teastainGit** [comment]
It looks exactly like a 
tft.setSwapBytes(true);
issue, where the two colour bytes are swapped, Big Endian-Little Endian issue, where Ox00FF is transposed to 0xFF00

**Comment by mmMicky** [comment]
Method 1: tft.setSwapBytes(true);
Method 2: Use the mouse to drag the blue and red to exchange

![image](https://user-images.githubusercontent.com/63094275/212444803-77fb32fe-9d59-4823-a666-cd46ff5739a5.png)

**Comment by tavdog** [comment]
Wow, thank you for the solution.  Dragging the Red block over to the blue fixed the issue.  But It never worked when I tried modifying swapBytes(true);  Why would setting swapBytes(false) not work, but dragging the little color swatch would ?

**Comment by tavdog** [comment]
The other solution that works is changing the following options in the user setup for tft_espi
// #define TFT_RGB_ORDER TFT_RGB  // Colour order Red-Green-Blue
#define TFT_RGB_ORDER TFT_BGR // Colour order Blue-Green-Red

**Comment by mmMicky** [comment]
swapBytes() is to modify the order of sending.
For example, the normal transmission is from bit7->bit6->....->bit0.
After enabling, the order is reversed even if bit0->bit1->..bit7
