### ISSUE TITLE
Ghost touches problem, hardware or software issue ?

### ISSUE THREAD

**Issue by onyx99** [Xinyuan-LilyGO/T-Display-S3#97]
Got 2x LilyGO TTGO T-Display-S3 ESP32-S3 - with 1.9 inch TFT Display and Touchscreen ordered, both of which are in the touch area
show so-called "Ghost touches", ie it seems that clicks occur spontaneously (with temperature differences or software glitch?).
take place on the screen, the other (2nd, same) device where exactly the same firmware has been flashed shows this problem less, but also occasionally appears

Tried to make the protective layer grease-free, also carefully remove the transparent protective layer
to see if the problem no longer showed itself, but the problem remained so I put the layer back on
overlaid carefully, notice that if the device is on for a while there are fewer ghost touches on the screen
take place, if I take the power off for a while or put the device in sleep mode and turn it on again, (more) random touches will take place again the software i used to test is the touch_test on the official github page.

**Comment by lewisxhe** [comment]
If ghost touch occurs, there may be a problem with the touch screen
